---
- name: install helm charts
  hosts: kube_control_plane[0]
  gather_facts: no
  roles:
    - name: helm-apps
      releases:
        - name: nfs-subdir-external-provisioner
          namespace: kube-system
          chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
      repositories:
        - name: nfs-subdir-external-provisioner
          url: "https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner"
      release_common_opts:
        wait_timeout: "5m"