---
dependencies:
  - role: kubernetes-apps/network_plugin/calico
    when: kube_network_plugin == 'calico'
    tags:
      - calico

  - role: kubernetes-apps/network_plugin/flannel
    when: kube_network_plugin == 'flannel'
    tags:
      - flannel

  - role: kubernetes-apps/network_plugin/kube-ovn
    when: kube_network_plugin == 'kube-ovn'
    tags:
      - kube-ovn

  - role: kubernetes-apps/network_plugin/weave
    when: kube_network_plugin == 'weave'
    tags:
      - weave

  - role: kubernetes-apps/network_plugin/kube-router
    when: kube_network_plugin == 'kube-router'
    tags:
      - kube-router
#2024/10/11 조건문 없으나 k8s-cluster.yml 안에 변수 있어서 boolean 조건문으로 변경해줌
#  - role: kubernetes-apps/network_plugin/multus
#    when: kube_network_plugin_multus
#    tags:
#      - multus
      
  - role: kubernetes-apps/network_plugin/multus
    when: kube_network_plugin_multus | bool
    tags:
      - multus
