---
dependencies:
  - role: network_plugin/cni

  - role: network_plugin/cilium
    when: kube_network_plugin == 'cilium' or cilium_deploy_additionally | default(false) | bool
    tags:
      - cilium

  - role: network_plugin/calico
    when: kube_network_plugin == 'calico'
    tags:
      - calico

  - role: network_plugin/flannel
    when: kube_network_plugin == 'flannel'
    tags:
      - flannel

  - role: network_plugin/weave
    when: kube_network_plugin == 'weave'
    tags:
      - weave

  - role: network_plugin/macvlan
    when: kube_network_plugin == 'macvlan'
    tags:
      - macvlan

  - role: network_plugin/kube-ovn
    when: kube_network_plugin == 'kube-ovn'
    tags:
      - kube-ovn

  - role: network_plugin/kube-router
    when: kube_network_plugin == 'kube-router'
    tags:
      - kube-router

  - role: network_plugin/custom_cni
    when: kube_network_plugin == 'custom_cni'
    tags:
      - custom_cni
      
#2024/10/11 조건문 없으나 k8s-cluster.yml 안에 변수 있어서 boolean 조건문으로 변경해줌
#  - role: network_plugin/multus
#    when: kube_network_plugin_multus | bool
#    tags:
#      - multus

#  - role: network_plugin/multus
#    when: kube_network_plugin_multus
#    tags:
#      - multus
